### PR TITLE
Added license information.

### PR DESCRIPTION
**Pull request by patriksvensson**

### CODE REVIEW

**Comment by patriksvensson** [comment]
@cake-build/team @martinwoodward Is [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/legalcode) OK for the graphics profile?

**Comment by gep13** [comment]
My gut still suggests that the non-commercial usage version would be more appropriate, although I can't really provide a clear justification as to why I think that 😄 :

https://creativecommons.org/licenses/by-nc/4.0/

So happy to be overruled on this.

**Comment by devlead** [comment]
I'm fine with both
[image Attribution (by)](http://creativecommons.org/licenses/by/4.0/)
and
[image NonCommercial (nc)](https://creativecommons.org/licenses/by-nc/4.0/)
So I'll let majority rule, but if it's a tie I'm leaning towards "Attribution (by)".

**Comment by martinwoodward** [comment]
[CC-BY](http://creativecommons.org/licenses/by/4.0/) would be my preference of the two. For the main [.NET Foundation Graphics repo](https://github.com/dotnet/swag) we use [CC0](https://github.com/dotnet/swag/blob/master/LICENSE) (i.e. equivalent to public domain) to allow for maximum re-use of the graphics.

**Comment by gep13** [comment]
@martinwoodward ah, so if we wanted to add the Cake Icon to the mix for icons in the swag repo, we would need to match that CC0 license?

**Comment by martinwoodward** [comment]
Not strictly speaking - there is no reason why you couldn't submit it to the swag repo as well under the CC0 license.

**Comment by gep13** [comment]
@cake-build/team so, what was the upshot of this?  Are we ready to merge this in?

**Comment by martinwoodward** [comment]
I'm happy with the choice of license FWIW

**Comment by devlead** [comment]
:shipit: 👍

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
